---
development:
  cloud_name: yarasol
  api_key: '689642437299612'
  api_secret: nHQezDlozuxcFkYO3110qjpPhfc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: yarasol
  api_key: '689642437299612'
  api_secret: nHQezDlozuxcFkYO3110qjpPhfc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: yarasol
  api_key: '689642437299612'
  api_secret: nHQezDlozuxcFkYO3110qjpPhfc
  enhance_image_tag: true
  static_image_support: false
