---
development:
  cloud_name: hthamovrr
  api_key: '739958196977861'
  api_secret: -buiDneBOqUP8SXZpYfTfQI-byg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hthamovrr
  api_key: '739958196977861'
  api_secret: -buiDneBOqUP8SXZpYfTfQI-byg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hthamovrr
  api_key: '739958196977861'
  api_secret: -buiDneBOqUP8SXZpYfTfQI-byg
  enhance_image_tag: true
  static_image_support: false
