development:
  adapter: postgresql
  username: webworks
  password: webworks
  encoding: utf8
  database: sarvjal_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  username: webworks
  password: webworks
  encoding: utf8
  database: sarvjal_test
  pool: 5
  host: localhost

production:
  encoding: utf8
  database: sarvjal_production
  pool: 5
