development:
  adapter: postgresql
  username: webworks
  password: webworks
  encoding: utf8
  database: yarasol_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  username: webworks
  password: webworks
  encoding: utf8
  database: yarasol_test
  pool: 5
  host: localhost

production:
  encoding: utf8
  database: yarasol_production
  pool: 5
